--- 
- name: "Register Redhat subscription"
  gather_facts: True
  hosts: all
  tasks:
    - name: Register Redhat subscription and attach automatically
      redhat_subscription:
        state: present
        username: "{{redhat_subscription_user}}"
        password: "{{redhat_subscription_pwd}}"
        autosubscribe: true
